
project_id = "ootziscicbahucatxyme"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "IPv6"

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://localhost:5173"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[functions]
enabled = true
port = 54324

[functions.n8n-workflows]
verify_jwt = true

[functions.n8n-workflows.environment]
N8N_API_URL = "https://intellywave.app.n8n.cloud/api/v1"
N8N_API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYzY1N2VlYy1lY2ExLTQzZjgtODJhZS01MzU1YWI0NDdjNmIiLCJpc3MiOiJuOG4iLCJhdWQiOiJwdWJsaWMtYXBpIiwiaWF0IjoxNzQzNjgyNTUzfQ.-LBPKIwxsgdiIiMgLf_9SRwS20kbZk5URnH1cHKB41Y"
