
project_id = "ootziscicbahucatxyme"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[realtime]
enabled = true

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
site_url = "http://localhost:3000"

[functions]
[functions.generate-contact-suggestion]
verify_jwt = true

[functions.google-jobs-scraper]
verify_jwt = false
