
project_id = "your-project-id"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "extensions"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[storage]
enabled = true

[functions.website-scraper]
verify_jwt = true

[functions.generate-search-string]
verify_jwt = true
