
project_id = "ootziscicbahucatxyme"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
site_url = "http://localhost:3000"

[storage]
enabled = true

[realtime]
enabled = true

[functions.instantly-api]
verify_jwt = true

[functions.analyze-email]
verify_jwt = false

[functions.gmail-auth]
verify_jwt = false

[functions.outlook-auth]
verify_jwt = false

[functions.website-crawler]
verify_jwt = false

[functions.n8n-workflows]
verify_jwt = true
