
project_id = "ootziscicbahucatxyme"

[functions.get-user-search-strings]
verify_jwt = false

[functions.create-search-string]
verify_jwt = true

[functions.generate-search-string]
verify_jwt = true

[functions.check-rls]
verify_jwt = false

