
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ootziscicbahucatxyme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vdHppc2NpY2JhaHVjYXR4eW1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MTk3NTQsImV4cCI6MjA1ODQ5NTc1NH0.HFbdZNFqQueDWd_fGA7It7ff7BifYYFsTWZGhKUT-xI";

// Create client with types
const supabaseClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Create a proxy to handle custom tables not yet in the type definitions
export const supabase = new Proxy(supabaseClient, {
  get(target, prop) {
    // If the property already exists, return it directly
    if (prop in target) {
      return (target as any)[prop];
    }
    
    // Handle 'from' specially to support queries to non-typed tables
    if (prop === 'from') {
      return (tableName: string) => {
        // Special case for ai_training_jobs to ensure it works even if types aren't fully generated
        if (tableName === 'ai_training_jobs') {
          return (target as any).from('ai_training_jobs');
        }
        
        // Use type assertion to bypass type checking for custom tables
        return (target as any).from(tableName);
      };
    }
    
    // Custom RPC function for checking RLS policies
    if (prop === 'rpc' && typeof target.rpc === 'function') {
      const originalRpc = target.rpc;
      return function(functionName: string, params?: any) {
        if (functionName === 'check_rls_policies') {
          // This is a client-side helper that makes a call to our Edge Function
          return target.functions.invoke('check-rls', {
            method: 'POST'
          });
        }
        // Call the original rpc function for other cases
        return originalRpc.call(target, functionName, params);
      };
    }
    
    return (target as any)[prop];
  }
});

// Export the raw client for cases when explicit types are needed
export const supabaseRaw = supabaseClient;
